use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::godel;
use crate::obsmem_adapter::ObsMemAdapter;
use crate::obsmem_retrieval_policy::{
    explain_policy_results, ExplainedMemoryRecord, RetrievalOrder, RetrievalPolicyV1,
    RetrievalRequest,
};
use crate::obsmem_store::FileObsMemClient;

use super::write_file;

pub(super) const DEMO_D_FAILURE_SIGNAL_JSON: &str = r#"{
  "schema_version": "godel_failure_signal.v1",
  "run_id": "demo-d-run-001",
  "workflow_id": "godel-obsmem-demo",
  "failure_code": "tool_failure",
  "failure_summary": "bounded deterministic failure signal for demo",
  "evidence_refs": [
    "runs/demo-d-run-001/logs/activation_log.json",
    "runs/demo-d-run-001/run_status.json"
  ]
}
"#;

pub(super) const DEMO_D_README_MD: &str = r#"# Demo D Output — Gödel + ObsMem Loop

Generated by:

```bash
cargo run --manifest-path adl/Cargo.toml --bin adl -- demo demo-d-godel-obsmem-loop --run --trace --out ./out
```

This demo executes the bounded Gödel stage loop and persists:

- `runs/demo-d-run-001/godel/canonical_evidence_view.v1.json`
- `runs/demo-d-run-001/godel/experiment_record.runtime.v1.json`
- `runs/demo-d-run-001/godel/obsmem_index_entry.runtime.v1.json`
- `godel_obsmem_demo_summary.json`
- `trace.jsonl`
"#;

pub(super) const DEMO_F_README_MD: &str = r#"# Demo F Output — ObsMem Retrieval

Generated by:

```bash
cargo run --manifest-path adl/Cargo.toml --bin adl -- demo demo-f-obsmem-retrieval --run --trace --out ./out
```

This demo seeds deterministic runtime experiment/index artifacts and performs deterministic retrieval by:

- `failure_code`
- explicit evidence-aware ranking explanations
- provenance families derived from cited artifacts
- deterministic tie-break values for equal-ranked hits

Primary artifacts:
- `runs/demo-f-run-a/godel/experiment_record.runtime.v1.json`
- `runs/demo-f-run-a/godel/obsmem_index_entry.runtime.v1.json`
- `runs/demo-f-run-b/godel/experiment_record.runtime.v1.json`
- `runs/demo-f-run-b/godel/obsmem_index_entry.runtime.v1.json`
- `runs/demo-f-run-c/godel/experiment_record.runtime.v1.json`
- `runs/demo-f-run-c/godel/obsmem_index_entry.runtime.v1.json`
- `obsmem_retrieval_result.json`
- `trace.jsonl`
"#;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
struct DemoObsMemQueryDescriptor {
    workflow_id: Option<String>,
    failure_code: Option<String>,
    tags: Vec<String>,
    limit: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
struct DemoObsMemOrderingDescriptor {
    policy_order: String,
    tie_break_fields: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
struct DemoObsMemRetrievalArtifact {
    schema_version: String,
    shared_store_path: String,
    query: DemoObsMemQueryDescriptor,
    ordering: DemoObsMemOrderingDescriptor,
    result_count: usize,
    entries: Vec<crate::obsmem_contract::MemoryRecord>,
    explained_results: Vec<ExplainedMemoryRecord>,
}

pub(super) fn run_godel_stage_loop_demo(out_dir: &Path) -> Result<Vec<PathBuf>> {
    let mut artifacts = Vec::new();
    let runs_root = out_dir.join("runs");
    let exec = godel::GodelStageLoopExecutor::new(godel::StageLoopConfig::default());
    let input = godel::StageLoopInput {
        run_id: "demo-d-run-001".to_string(),
        workflow_id: "godel-obsmem-demo".to_string(),
        failure_code: "tool_failure".to_string(),
        failure_summary: "bounded deterministic failure signal for demo".to_string(),
        evidence_refs: vec![
            "runs/demo-d-run-001/logs/activation_log.json".to_string(),
            "runs/demo-d-run-001/run_status.json".to_string(),
        ],
    };
    let persisted = exec.execute_and_persist(&input, &runs_root)?;
    let summary = serde_json::json!({
        "schema_version": "godel_obsmem_demo_summary.v1",
        "run_id": persisted.run.record.run_id,
        "stage_order": persisted
            .run
            .stage_order
            .iter()
            .map(|s| s.as_str())
            .collect::<Vec<_>>(),
        "hypothesis_count": persisted.run.hypotheses.len(),
        "selected_hypothesis_id": persisted.run.hypothesis.id,
        "selected_mutation_id": persisted.run.mutation.id,
        "canonical_mutation_rel_path": persisted.canonical_mutation_rel_path,
        "evaluation_decision": format!("{:?}", persisted.run.evaluation.decision).to_lowercase(),
        "canonical_evaluation_plan_rel_path": persisted.canonical_evaluation_plan_rel_path,
        "canonical_evidence_rel_path": persisted.canonical_evidence_rel_path,
        "experiment_record_rel_path": persisted.experiment_record_rel_path,
        "obsmem_index_rel_path": persisted.obsmem_index_rel_path
    });
    artifacts.push(write_file(
        out_dir,
        "godel_obsmem_demo_summary.json",
        &serde_json::to_string_pretty(&summary)?,
    )?);
    artifacts.push(out_dir.join("runs/demo-d-run-001/godel/evaluation_plan.v1.json"));
    artifacts.push(out_dir.join("runs/demo-d-run-001/godel/mutation.v1.json"));
    artifacts.push(out_dir.join("runs/demo-d-run-001/godel/canonical_evidence_view.v1.json"));
    artifacts.push(out_dir.join("runs/demo-d-run-001/godel/evaluation_plan.v1.json"));
    artifacts.push(out_dir.join("runs/demo-d-run-001/godel/experiment_record.runtime.v1.json"));
    artifacts.push(out_dir.join("runs/demo-d-run-001/godel/obsmem_index_entry.runtime.v1.json"));
    Ok(artifacts)
}

pub(super) fn seed_obsmem_retrieval_demo(out_dir: &Path) -> Result<Vec<PathBuf>> {
    let mut artifacts = Vec::new();
    let runs_root = out_dir.join("runs");
    let exec = godel::GodelStageLoopExecutor::new(godel::StageLoopConfig::default());

    let runs = [
        (
            "demo-f-run-a",
            "deterministic failure A",
            "success",
            vec!["runs/demo-f-run-a/run_status.json".to_string()],
        ),
        (
            "demo-f-run-b",
            "deterministic failure B",
            "success",
            vec!["runs/demo-f-run-b/run_status.json".to_string()],
        ),
        (
            "demo-f-run-c",
            "deterministic failure C",
            "failed",
            vec!["runs/demo-f-run-c/run_status.json".to_string()],
        ),
    ];

    for (run_id, failure_summary, overall_status, evidence_refs) in runs {
        let input = godel::StageLoopInput {
            run_id: run_id.to_string(),
            workflow_id: "godel-retrieval-demo".to_string(),
            failure_code: "tool_failure".to_string(),
            failure_summary: failure_summary.to_string(),
            evidence_refs,
        };
        let persisted = exec.execute_and_persist(&input, &runs_root)?;
        write_demo_obsmem_runtime_artifacts(
            &runs_root,
            run_id,
            "godel-retrieval-demo",
            overall_status,
            "tool_failure",
        )?;
        artifacts.push(out_dir.join(&persisted.experiment_record_rel_path));
        artifacts.push(out_dir.join(&persisted.obsmem_index_rel_path));
    }

    Ok(artifacts)
}

pub(super) fn query_obsmem_retrieval_demo(out_dir: &Path) -> Result<Vec<PathBuf>> {
    let runs_root = out_dir.join("runs");
    let shared_store_path = runs_root.join("_shared").join("obsmem_store.v1.json");
    let adapter = ObsMemAdapter::new(FileObsMemClient::new(&shared_store_path));

    for run_id in ["demo-f-run-a", "demo-f-run-b", "demo-f-run-c"] {
        adapter
            .index_run_from_artifacts(&runs_root, run_id)
            .with_context(|| format!("index demo ObsMem artifacts for '{run_id}'"))?;
    }

    let mut policy = RetrievalPolicyV1 {
        default_limit: 10,
        required_tags: vec!["workflow:godel-retrieval-demo".to_string()],
        required_failure_code: Some("tool_failure".to_string()),
        order: RetrievalOrder::EvidenceAdjustedDescIdAsc,
    };
    policy.normalize();

    let request = RetrievalRequest {
        workflow_id: Some("godel-retrieval-demo".to_string()),
        failure_code: None,
        tags: vec![],
        limit_override: Some(10),
    };

    let query = request
        .to_query(&policy)
        .context("build deterministic ObsMem demo query")?;
    let raw_result = adapter
        .query(
            query.workflow_id.as_deref(),
            query.failure_code.as_deref(),
            &query.tags,
            query.limit,
        )
        .context("query deterministic ObsMem demo results")?;
    let explained = explain_policy_results(&policy, &request, raw_result)
        .context("derive deterministic ObsMem ranking explanations")?;
    let entries = explained
        .iter()
        .map(|entry| entry.record.clone())
        .collect::<Vec<_>>();

    let result = DemoObsMemRetrievalArtifact {
        schema_version: "obsmem_retrieval_result.demo.v2".to_string(),
        shared_store_path: "runs/_shared/obsmem_store.v1.json".to_string(),
        query: DemoObsMemQueryDescriptor {
            workflow_id: query.workflow_id,
            failure_code: query.failure_code,
            tags: query.tags,
            limit: query.limit,
        },
        ordering: DemoObsMemOrderingDescriptor {
            policy_order: "evidence_adjusted_desc_id_asc".to_string(),
            tie_break_fields: vec![
                "id".to_string(),
                "run_id".to_string(),
                "workflow_id".to_string(),
                "payload".to_string(),
            ],
        },
        result_count: explained.len(),
        entries,
        explained_results: explained,
    };

    let path = write_file(
        out_dir,
        "obsmem_retrieval_result.json",
        &serde_json::to_string_pretty(&result)?,
    )?;
    Ok(vec![path, shared_store_path])
}

fn write_demo_obsmem_runtime_artifacts(
    runs_root: &Path,
    run_id: &str,
    workflow_id: &str,
    overall_status: &str,
    failure_kind: &str,
) -> Result<()> {
    let run_dir = runs_root.join(run_id);
    std::fs::create_dir_all(run_dir.join("logs"))
        .with_context(|| format!("failed to create '{}'", run_dir.display()))?;

    let run_summary = serde_json::json!({
        "run_summary_version": 1,
        "run_id": run_id,
        "workflow_id": workflow_id,
    });
    std::fs::write(
        run_dir.join("run_summary.json"),
        serde_json::to_vec_pretty(&run_summary).context("serialize demo run_summary.json")?,
    )
    .with_context(|| format!("failed to write '{}/run_summary.json'", run_dir.display()))?;

    let run_status = serde_json::json!({
        "run_status_version": 1,
        "run_id": run_id,
        "overall_status": overall_status,
        "failure_kind": failure_kind,
    });
    std::fs::write(
        run_dir.join("run_status.json"),
        serde_json::to_vec_pretty(&run_status).context("serialize demo run_status.json")?,
    )
    .with_context(|| format!("failed to write '{}/run_status.json'", run_dir.display()))?;

    let activation = serde_json::json!({
        "activation_log_version": 1,
        "ordering": "append_only_emission_order",
        "stable_ids": {
            "step_id": "stable within resolved execution plan",
            "delegation_id": "deterministic per run: del-<counter>",
            "run_id": "run-scoped identifier; not replay-stable across independent runs",
        },
        "events": [
            {
                "kind": "StepStarted",
                "step_id": "seed",
                "agent_id": "demo-obsmem",
                "provider_id": "local",
                "task_id": "seed",
                "delegation_json": null
            },
            {
                "kind": "StepFinished",
                "step_id": "seed",
                "success": overall_status == "success"
            }
        ]
    });
    std::fs::write(
        run_dir.join("logs").join("activation_log.json"),
        serde_json::to_vec_pretty(&activation).context("serialize demo activation_log.json")?,
    )
    .with_context(|| {
        format!(
            "failed to write '{}/logs/activation_log.json'",
            run_dir.display()
        )
    })?;
    Ok(())
}
