#!/usr/bin/env bash
set -euo pipefail

ROOT="${1:-.adl/reports}"
LATEST_SCRIPT="swarm/tools/update_latest_reports.sh"

[[ -d "$ROOT" ]] || { echo "missing reports root: $ROOT" >&2; exit 1; }
[[ -x "$LATEST_SCRIPT" ]] || { echo "missing executable: $LATEST_SCRIPT" >&2; exit 1; }

"$LATEST_SCRIPT" "$ROOT" >/dev/null

OUT="${ROOT}/INDEX.md"
{
  echo "# Reports Index"
  echo
  echo "Generated by: \`swarm/tools/update_reports_index.sh\`"
  echo
  for family in automation burst pr-cycle; do
    dir="${ROOT}/${family}"
    [[ -d "$dir" ]] || continue
    echo "## ${family}"
    echo
    for child in "$dir"/*; do
      [[ -d "$child" ]] || continue
      base="$(basename "$child")"
      latest_path="${child}/LATEST.md"
      if [[ -f "$latest_path" ]]; then
        latest="$(awk '/^- \.\// { gsub("^- \\./",""); gsub("/$",""); print; exit }' "$latest_path")"
      else
        latest=""
      fi
      if [[ -n "$latest" ]]; then
        echo "- \`${family}/${base}\`: latest \`${latest}\`"
      else
        echo "- \`${family}/${base}\`: no latest pointer"
      fi
    done
    echo
  done
} >"$OUT"

echo "updated report index: $OUT"
