use anyhow::{bail, Result};
use std::fs;
use std::path::Path;

#[derive(Clone, Copy)]
pub(crate) enum PromptSurfaceKind {
    IssuePrompt,
    Stp,
    Sip,
}

impl PromptSurfaceKind {
    fn label(self) -> &'static str {
        match self {
            Self::IssuePrompt => "issue body/source prompt",
            Self::Stp => "stp",
            Self::Sip => "sip",
        }
    }
}

pub(crate) fn validate_authored_prompt_surface(
    phase: &str,
    path: &Path,
    kind: PromptSurfaceKind,
) -> Result<()> {
    let text = fs::read_to_string(path)?;
    if let Some(reason) = bootstrap_stub_reason(&text, kind) {
        bail!(
            "{phase}: {} is still bootstrap stub content ({reason}): {}",
            kind.label(),
            path.display()
        );
    }
    Ok(())
}

pub(crate) fn placeholder_issue_body_reason(text: &str) -> Option<&'static str> {
    let normalized = text.replace("\r\n", "\n");
    if normalized.contains("## Goal\n-\n\n## Acceptance Criteria\n-") {
        return Some("placeholder goal/acceptance criteria stub");
    }
    if !section_has_authored_content(&normalized, "## Goal") {
        return Some("empty Goal section");
    }
    if !section_has_authored_content(&normalized, "## Acceptance Criteria") {
        return Some("empty Acceptance Criteria section");
    }
    None
}

pub(crate) fn bootstrap_stub_reason(text: &str, kind: PromptSurfaceKind) -> Option<&'static str> {
    let normalized = text.replace("\r\n", "\n");
    if let Some(reason) = placeholder_issue_body_reason(&normalized) {
        return Some(reason);
    }

    match kind {
        PromptSurfaceKind::IssuePrompt | PromptSurfaceKind::Stp => {
            let issue_prompt_markers = [
                "Bootstrap-generated local source prompt for issue #",
                "Bootstrap-generated issue body created from the requested title and labels so the issue starts with a readable, reviewable task surface instead of a placeholder stub.",
                "Bootstrap-generated workflow-skill issue body created from the requested title and labels so the issue starts with a concrete first draft instead of a generic bootstrap stub.",
                "Ship one bounded, reviewable ADL task derived from the requested title and labels using the tracked issue/task-bundle workflow.",
                "Define one bounded workflow-skill or tooling-surface change in the tracked PR workflow substrate and make the resulting source prompt/STP concrete enough for qualitative review before execution.",
                "The default required outcome type for this issue is `",
                "the issue title and labels are reflected in the authored issue body",
                "the GitHub issue body and local source prompt stay aligned with the current workflow",
                "the generated prompt identifies this as a workflow-skill/tooling issue rather than a generic bootstrap task",
                "Translate the GitHub issue into the canonical local STP/task-bundle flow and refine this prompt before execution as needed.",
                "Generated by `pr.sh` bootstrap fallback.",
                "This prompt was generated automatically because the canonical local issue prompt was missing.",
                "Bootstrap-generated from GitHub issue metadata because no canonical local issue prompt existed yet.",
                "Generated by the ADL PR control plane from issue metadata.",
                "Generated by the ADL PR control plane from issue metadata using the workflow-skill bootstrap template.",
                "Default next steps should follow `pr-ready` and `pr-run`, not the older `pr start` path.",
            ];
            if issue_prompt_markers
                .iter()
                .any(|marker| normalized.contains(marker))
            {
                return Some("bootstrap-generated issue prompt template text");
            }
        }
        PromptSurfaceKind::Sip => {
            let sip_markers = [
                "- State whether this issue must ship code, docs, tests, demo artifacts, or a combination.",
                "- Likely files, modules, docs, commands, schemas, or artifacts to modify or validate",
                "- Required commands:",
                "- Required tests:",
                "- Required artifacts / traces:",
                "- Required reviewer or demo checks:",
                "- Required demo(s):",
                "- Required proof surface(s):",
                "- If no demo is required, say why:",
                "- Determinism requirements:",
                "- Security / privacy requirements:",
                "- Resource limits (time/CPU/memory/network):",
            ];
            if normalized
                .lines()
                .map(str::trim)
                .any(|line| sip_markers.contains(&line))
            {
                return Some("unrefined SIP template guidance");
            }
        }
    }
    None
}

fn section_has_authored_content(text: &str, header: &str) -> bool {
    let mut in_section = false;
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed == header {
            in_section = true;
            continue;
        }
        if in_section {
            if trimmed.starts_with("## ") {
                return false;
            }
            if !trimmed.is_empty() {
                return true;
            }
        }
    }
    false
}
